[2020-02-04 13:33:22 +0000] [15896] [INFO] Starting gunicorn 19.7.1
[2020-02-04 13:33:22 +0000] [15896] [INFO] Listening at: http://0.0.0.0:8000 (15896)
[2020-02-04 13:33:22 +0000] [15896] [INFO] Using worker: sync
[2020-02-04 13:33:22 +0000] [15899] [INFO] Booting worker with pid: 15899
[2020-02-04 13:33:22 +0000] [15899] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'evalmgr.wsgi'
[2020-02-04 13:33:22 +0000] [15899] [INFO] Worker exiting (pid: 15899)
[2020-02-04 13:33:22 +0000] [15896] [INFO] Shutting down: Master
[2020-02-04 13:33:22 +0000] [15896] [INFO] Reason: Worker failed to boot.
[2020-02-04 14:52:49 +0000] [16233] [INFO] Starting gunicorn 19.7.1
[2020-02-04 14:52:49 +0000] [16233] [INFO] Listening at: http://0.0.0.0:8000 (16233)
[2020-02-04 14:52:49 +0000] [16233] [INFO] Using worker: sync
[2020-02-04 14:52:49 +0000] [16236] [INFO] Booting worker with pid: 16236
[2020-02-04 14:52:49 +0000] [16236] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'evalmgr.wsgi'
[2020-02-04 14:52:49 +0000] [16236] [INFO] Worker exiting (pid: 16236)
[2020-02-04 14:52:49 +0000] [16233] [INFO] Shutting down: Master
[2020-02-04 14:52:49 +0000] [16233] [INFO] Reason: Worker failed to boot.
